-- SELECT 'DROP TABLE IF EXISTS '||tablename||' CASCADE;' FROM pg_tables;

DROP TABLE IF EXISTS cidade CASCADE;
DROP TABLE IF EXISTS bemcultural CASCADE;
DROP TABLE IF EXISTS bemcultural_palavraschave CASCADE;
DROP TABLE IF EXISTS espacopublico CASCADE;
DROP TABLE IF EXISTS relatorio_espacopublico CASCADE;
DROP TABLE IF EXISTS museu CASCADE;
DROP TABLE IF EXISTS estudio CASCADE;
DROP TABLE IF EXISTS cinemateca CASCADE;
DROP TABLE IF EXISTS monumento CASCADE;
DROP TABLE IF EXISTS edificacaotombada CASCADE;
DROP TABLE IF EXISTS edificacaotombada_proprietarios CASCADE;
DROP TABLE IF EXISTS obra CASCADE;
DROP TABLE IF EXISTS obra_autores CASCADE;
DROP TABLE IF EXISTS musica CASCADE;
DROP TABLE IF EXISTS musica_genero CASCADE;
DROP TABLE IF EXISTS musica_compositor CASCADE;
DROP TABLE IF EXISTS filme CASCADE;
DROP TABLE IF EXISTS filme_creditos CASCADE;
DROP TABLE IF EXISTS cidadao CASCADE;
DROP TABLE IF EXISTS visita CASCADE;
DROP TABLE IF EXISTS denuncia CASCADE;
DROP TABLE IF EXISTS agprefeitura CASCADE;
DROP TABLE IF EXISTS auditoria CASCADE;
DROP TABLE IF EXISTS evento CASCADE;
DROP TABLE IF EXISTS confirmaparticipacao CASCADE;

DROP FUNCTION IF EXISTS quem_denunciou CASCADE;
DROP FUNCTION IF EXISTS checa_cidade CASCADE;

DROP SEQUENCE IF EXISTS S_BCULTURAL CASCADE;
DROP SEQUENCE IF EXISTS S_DENUNCIA CASCADE;
